import assert from 'node:assert/strict'
import { test } from './api-test.mjs'
import { addCaptcha, editCaptcha } from './ui.mjs'

// Real local API and isolated state only. No check-in, SMS or exchange calls.
const origin = 'http://127.0.0.1:5897'
test('隔离真实 API 的建站、账号管理、设置与退出', async ({ browser }, testInfo) => {
const context = await browser.newContext({ viewport: { width: 1366, height: 1000 }, reducedMotion: 'reduce', timezoneId: 'Asia/Shanghai' })
await context.addInitScript(() => localStorage.setItem('miyohub:auto-save', 'false'))
const page = await context.newPage()
const errors = []
page.setDefaultTimeout(8000)
page.on('pageerror', e => errors.push(e.message))
await context.route('**/*', async route => {
  const url = new URL(route.request().url())
  if (url.origin !== origin || /\/api\/v1\/(shop\/(?!status|plans$)|run|login\/|accounts\/check|push\/)/.test(url.pathname)) {
    errors.push('External-effect request denied: ' + url.pathname)
    return route.abort()
  }
  return route.continue()
})
try {
  await page.goto(origin)
  await page.getByRole('heading', { name: '创建管理员账号' }).waitFor()
  await page.getByLabel('用户名', { exact: true }).fill('smoke-admin')
  await page.getByLabel('密码', { exact: true }).fill('local-test-only-123')
  await page.getByRole('button', { name: '创建并进入' }).click()
  await page.locator('.metrics').waitFor()
  await page.getByRole('dialog', { name: '快速配置', exact: true }).getByRole('button', { name: '关闭弹窗', exact: true }).click()
  await page.getByText('尚未绑定米游社账号', { exact: true }).waitFor()
  await page.getByRole('button', { name: '已有 Cookie？手动添加账号', exact: true }).click()
  let dialog = page.getByRole('dialog')
  await dialog.getByLabel('账号名称', { exact: true }).fill('隔离测试账号')
  await dialog.getByLabel('Cookie', { exact: true }).fill('stuid=100;cookie_token=local-test-only')
  await dialog.getByLabel('云·原神', { exact: true }).fill('cloud-test-only')
  await dialog.getByLabel('暂停此账号的签到与兑换').check()
  await dialog.getByRole('button', { name: '保存账号', exact: true }).click()
  await dialog.waitFor({ state: 'hidden' })
  const card = page.locator('.account-card').filter({ hasText: '隔离测试账号' })
  await card.waitFor()
  assert(await card.getByRole('button', { name: '签到', exact: true }).isDisabled())
  assert.equal(await page.evaluate(() => document.body.style.overflow), '')
  const response = await context.request.get(origin + '/api/v1/accounts')
  const body = await response.json()
  assert(body.ok && body.data.length === 1)
  assert.equal(body.data[0].cookie, '')
  assert.equal(body.data[0].stoken, '')
  assert.deepEqual(body.data[0].cloud_configured, ['genshin'])
  assert.equal(body.data[0].disabled, true)
  await card.getByRole('button', { name: '管理', exact: true }).click()
  dialog = page.getByRole('dialog')
  assert.equal(await dialog.getByLabel('Cookie', { exact: true }).inputValue(), '')
  await dialog.getByLabel('账号名称', { exact: true }).fill('改名后的测试账号')
  await dialog.getByLabel('清除云·原神凭据', { exact: true }).check()
  await dialog.getByRole('button', { name: '保存账号', exact: true }).click()
  await dialog.waitFor({ state: 'hidden' })
  const renamed = page.locator('.account-card').filter({ hasText: '改名后的测试账号' })
  await renamed.waitFor()
  await renamed.getByRole('button', { name: '管理', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '删除账号', exact: true }).click()
  await renamed.getByRole('button', { name: '保留账号', exact: true }).click()
  assert.equal(await page.locator('.account-card').count(), 1)
  await renamed.getByRole('button', { name: '管理', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '删除账号', exact: true }).click()
  await renamed.getByRole('button', { name: '确认删除', exact: true }).click()
  await page.getByText('尚未绑定米游社账号', { exact: true }).waitFor()
  await page.getByRole('navigation', { name: '主导航', exact: true }).getByRole('button', { name: '系统设置', exact: true }).click()
  await page.getByRole('heading', { name: '运行与每日调度', exact: true }).waitFor()
  assert(await page.getByRole('button', { name: '保存设置', exact: true }).isDisabled(), 'unchanged settings should not ask to be saved')
  await page.getByLabel('默认调度随机延迟上限（分钟）', { exact: true }).fill('7')
  await page.getByRole('button', { name: '保存设置', exact: true }).click()
  await page.getByText('设置已保存并生效', { exact: true }).waitFor()
  // Exercise captcha configuration against the real isolated API. Saving
  // configuration must never call a solver or start an account task.
  const captchaPanel = page.locator('.captcha-panel')
  await captchaPanel.getByRole('button', { name: '移除验证码渠道 1', exact: true }).click()
  await addCaptcha(page, captchaPanel, 'custom', async dialog => {
    await dialog.getByLabel('接口地址', { exact: true }).fill('http://captcha:9645/pass_nine')
    await dialog.getByLabel(/Bearer Token/).fill('captcha-local-private')
    await dialog.getByLabel('启用这个渠道', { exact: true }).check()
  })
  await addCaptcha(page, captchaPanel, 'damagou', async dialog => {
    await dialog.getByLabel(/打码狗 UserKey/).fill('captcha-paid-private')
    await dialog.getByLabel('启用这个渠道', { exact: true }).check()
  })
  await page.getByRole('button', { name: '保存设置', exact: true }).click()
  await page.getByText('设置已保存并生效', { exact: true }).waitFor()
  let captchaConfig = (await (await context.request.get(origin + '/api/v1/config')).json()).data.captcha
  assert.deepEqual(captchaConfig.channels.map(c => c.provider), ['custom', 'damagou'])
  assert(captchaConfig.channels.every(c => !c.userkey && !c.token))
  assert.deepEqual(captchaConfig.channels.map(c => c.configured), [['token'], ['userkey']])
  await captchaPanel.getByRole('button', { name: '配置验证码渠道 1', exact: true }).click()
  assert.equal(await page.getByRole('dialog').getByLabel(/Bearer Token/).inputValue(), '')
  await page.getByRole('dialog').getByRole('button', { name: '取消', exact: true }).click()
  await captchaPanel.getByRole('button', { name: '上移验证码渠道 2', exact: true }).click()
  await page.getByRole('button', { name: '保存设置', exact: true }).click()
  await page.getByText('设置已保存并生效', { exact: true }).waitFor()
  captchaConfig = (await (await context.request.get(origin + '/api/v1/config')).json()).data.captcha
  assert.deepEqual(captchaConfig.channels.map(c => c.provider), ['damagou', 'custom'])
  assert.deepEqual(captchaConfig.channels.map(c => c.configured), [['userkey'], ['token']])
  await editCaptcha(page, captchaPanel, 2, dialog => dialog.getByLabel('接口地址', { exact: true }).fill('https://example.invalid/pass_uni'))
  await page.getByRole('button', { name: '保存设置', exact: true }).click()
  await page.getByText('设置已保存并生效', { exact: true }).waitFor()
  captchaConfig = (await (await context.request.get(origin + '/api/v1/config')).json()).data.captcha
  assert(!captchaConfig.channels[1].configured?.includes('token'), 'token followed a changed endpoint')
  await editCaptcha(page, captchaPanel, 2, dialog => dialog.getByLabel(/Bearer Token/).fill('replacement-private'))
  await page.getByRole('button', { name: '保存设置', exact: true }).click()
  await page.getByText('设置已保存并生效', { exact: true }).waitFor()
  await editCaptcha(page, captchaPanel, 2, dialog => dialog.getByLabel('保存时清除已配置 Token', { exact: true }).check())
  await page.getByRole('button', { name: '保存设置', exact: true }).click()
  await page.getByText('设置已保存并生效', { exact: true }).waitFor()
  captchaConfig = (await (await context.request.get(origin + '/api/v1/config')).json()).data.captcha
  assert(!captchaConfig.channels[1].configured?.includes('token'))
  await captchaPanel.screenshot({ path: testInfo.outputPath('captcha-services-desktop.png') })
  await page.getByRole('button', { name: '退出登录', exact: true }).click()
  await page.getByRole('heading', { name: '登录 MiyoHub', exact: true }).waitFor()
  assert.equal((await context.request.get(origin + '/api/v1/accounts')).status(), 401)
  assert.deepEqual(errors, [])
  await testInfo.attach('isolation-report', { body: JSON.stringify({ ok: true, upstreamOperations: 0 }), contentType: 'application/json' })
} catch (error) {
  await page.screenshot({ path: testInfo.outputPath('integration-failure.png'), fullPage: true }).catch(() => {})
  throw error
} finally { await context.close() }
})
