import assert from 'node:assert/strict'
import { expect, test } from './api-test.mjs'
import { addCaptcha, choose, dismissGuide } from './ui.mjs'

const origin = 'http://127.0.0.1:5897'
const headers = { 'Content-Type': 'application/json', 'X-MiyoHub-Request': '1' }

test('真实隔离 API：账号独立签到、管理员分别授权、个人打码与推送隔离', async ({ browser }, testInfo) => {
  const contexts = [], unsafe = [], browserErrors = []
  async function workspace(width) {
    const context = await browser.newContext({ viewport: { width, height: 950 }, reducedMotion: 'reduce', timezoneId: 'Asia/Shanghai' })
    await context.addInitScript(() => localStorage.setItem('miyohub:auto-save', 'false'))
    contexts.push(context)
    await context.route('**/*', async route => {
      const url = new URL(route.request().url()), path = url.pathname
      if (url.origin === origin && path === '/api/v1/shop/goods') return route.fulfill({ contentType: 'application/json', body: JSON.stringify({ ok: true, data: { games: [], goods: [] } }) })
      if (url.origin !== origin || /^\/api\/v1\/(run|login\/|accounts\/check|push\/(test|qr)|shop\/(?!status|plans$))/.test(path)) { unsafe.push(path); return route.abort() }
      return route.continue()
    })
    const page = await context.newPage()
    page.on('pageerror', error => browserErrors.push(error.message))
    return { context, page }
  }
  async function request(context, method, path, data) {
    const response = await context.request.fetch(origin + path, { method, headers, ...(data === undefined ? {} : { data }) })
    const result = await response.json()
    assert(response.ok() && result.ok, path + ': ' + (result.error || response.status()))
    return result.data
  }
  async function navigate(page, label) {
    if (page.viewportSize().width > 640) return page.getByRole('navigation', { name: '主导航', exact: true }).getByRole('button', { name: label, exact: true }).click()
    const nav = page.getByRole('navigation', { name: '移动导航', exact: true })
    if (['任务总览', '商品兑换', '消息推送'].includes(label)) return nav.getByRole('button', { name: label, exact: true }).click()
    await nav.getByRole('button', { name: '更多', exact: true }).click()
    await page.getByRole('navigation', { name: '更多导航', exact: true }).getByRole('button', { name: new RegExp(label) }).click()
  }
  async function noOverflow(page) { assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'horizontal overflow') }
  try {
    const admin = await workspace(1440), alice = await workspace(390), bob = await workspace(320)
    const status = await request(admin.context, 'GET', '/api/v1/auth/status')
    await request(admin.context, 'POST', status.has_admin ? '/api/v1/auth/login' : '/api/v1/auth/setup', { username: 'smoke-admin', password: 'local-test-only-123' })
    const userA = await request(admin.context, 'POST', '/api/v1/admin/users', { username: 'routine-alice', password: 'local-test-only-123', role: 'user' })
    const userB = await request(admin.context, 'POST', '/api/v1/admin/users', { username: 'routine-bob', password: 'local-test-only-123', role: 'user' })
    for (const [owner, name] of [[alice, 'routine-alice'], [bob, 'routine-bob']]) await request(owner.context, 'POST', '/api/v1/auth/login', { username: name, password: 'local-test-only-123' })
    for (const owner of [admin, alice, bob]) await dismissGuide(owner.context)
    await request(alice.context, 'POST', '/api/v1/accounts', { name: '原神日常号', cookie: 'stuid=200001;cookie_token=isolated-test-a' })
    await request(alice.context, 'POST', '/api/v1/accounts', { name: '星海备用号', cookie: 'stuid=200002;cookie_token=isolated-test-b' })
    await request(bob.context, 'POST', '/api/v1/accounts', { name: 'Bob 的账号', cookie: 'stuid=200003;cookie_token=isolated-test-c' })
    const initialA = await request(alice.context, 'GET', '/api/v1/accounts'), initialB = await request(bob.context, 'GET', '/api/v1/accounts')
    await alice.page.goto(origin)
    const card = alice.page.locator('.account-card').filter({ hasText: '原神日常号' })
    await card.getByRole('button', { name: '签到设置', exact: true }).click()
    let dialog = alice.page.getByRole('dialog', { name: '原神日常号 · 签到设置', exact: true })
    assert.equal(await dialog.locator('.sticky-modal-actions').evaluate(el => getComputedStyle(el).position), 'static', 'old sticky save bar obscures fields above the floating save')
    await dialog.getByLabel('参加每日自动签到', { exact: true }).uncheck()
    await dialog.getByLabel('星穹铁道签到', { exact: true }).uncheck()
    await dialog.getByLabel('绝区零签到', { exact: true }).uncheck()
    await dialog.getByRole('button', { name: '云游戏', exact: true }).click()
    await dialog.getByLabel('启用云游戏签到', { exact: true }).check()
    await dialog.getByLabel('云·绝区零签到', { exact: true }).uncheck()
    await dialog.getByRole('button', { name: '米游币', exact: true }).click()
    await dialog.getByLabel('启用米游币任务', { exact: true }).check()
    await dialog.getByLabel('看帖', { exact: true }).check()
    await dialog.getByLabel('原神', { exact: true }).uncheck()
    await dialog.getByLabel('大别野', { exact: true }).uncheck()
    await dialog.getByLabel('星穹铁道', { exact: true }).check()
    await dialog.getByText('执行间隔与更多参数', { exact: true }).click()
    await dialog.getByLabel('最多帖子数', { exact: true }).fill('4')
    await noOverflow(alice.page)
    const bounds = await dialog.boundingBox()
    assert(Math.abs(bounds.y + bounds.height - alice.page.viewportSize().height) < 2, 'mobile editor was not a bottom sheet')
    await alice.page.screenshot({ path: testInfo.outputPath('account-tasks-mobile.png') })
    await dialog.getByRole('button', { name: '保存签到设置', exact: true }).click()
    await dialog.waitFor({ state: 'hidden' })
    await card.getByText('仅手动签到', { exact: true }).waitFor()
    const afterA = await request(alice.context, 'GET', '/api/v1/accounts'), afterB = await request(bob.context, 'GET', '/api/v1/accounts')
    assert.deepEqual(afterA[0].task_settings.games.enabled, ['genshin'])
    assert.deepEqual(afterA[0].task_settings.cloud_games.enabled, ['genshin'])
    assert.deepEqual(afterA[0].task_settings.bbs.forums, [6])
    assert.equal(afterA[0].task_settings.bbs.post_limit, 4)
    assert.deepEqual(afterA[1].task_settings, initialA[1].task_settings)
    assert.deepEqual(afterB[0].task_settings, initialB[0].task_settings)
    assert.equal(afterA[0].exchange_allowed, false)
    const forbiddenTasks = await alice.context.request.put(origin + '/api/v1/accounts/tasks', { headers, data: { id: initialB[0].id, task_settings: afterA[0].task_settings } })
    assert.equal(forbiddenTasks.status(), 403)

    await navigate(alice.page, '打码服务')
    await expect(alice.page.getByRole('radio', { name: '使用站点打码服务', exact: true })).toBeDisabled()
    await alice.page.getByRole('radio', { name: '使用自己的打码服务', exact: true }).check()
    await addCaptcha(alice.page, alice.page.locator('.personal-captcha-panel'), 'custom', async editor => {
      await editor.getByLabel('接口地址', { exact: true }).fill('https://personal-solver.example/pass_nine')
      await editor.getByLabel(/Bearer Token/).fill('ISOLATED_ALICE_TOKEN')
      await editor.getByLabel('启用这个渠道', { exact: true }).check()
      await editor.getByRole('combobox', { name: '九宫格模型', exact: true }).click()
      await alice.page.keyboard.press('ArrowDown')
      await alice.page.keyboard.press('Enter')
      assert.equal(await alice.page.getByRole('listbox').count(), 0)
      assert.equal(await alice.page.evaluate(() => document.body.style.overflow), 'hidden')
    })
    await alice.page.getByRole('button', { name: '保存个人打码配置', exact: true }).click()
    await alice.page.getByText('个人打码配置已保存，仅对你的账号生效。', { exact: true }).waitFor()
    const ownCaptcha = await request(alice.context, 'GET', '/api/v1/captcha/config')
    assert.equal(ownCaptcha.source, 'personal')
    assert.equal(ownCaptcha.channels[0].token, '')
    assert.equal(ownCaptcha.channels[0].use_v3_model, false)
    assert.deepEqual(ownCaptcha.channels[0].configured, ['token'])
    assert.deepEqual((await request(bob.context, 'GET', '/api/v1/captcha/config')).channels, [])
    assert.deepEqual((await request(alice.context, 'GET', '/api/v1/config')).captcha.channels, [])
    await noOverflow(alice.page)
    await alice.page.screenshot({ path: testInfo.outputPath('personal-captcha-mobile.png'), fullPage: true })

    await admin.page.goto(origin + '/#admin')
    await admin.page.getByRole('button', { name: '管理用户 routine-alice', exact: true }).click()
    dialog = admin.page.getByRole('dialog', { name: 'routine-alice · 用户设置', exact: true })
    await dialog.getByLabel('授予站点打码权限', { exact: true }).check()
    assert(!await dialog.getByLabel('授予商品兑换权限', { exact: true }).isChecked())
    await noOverflow(admin.page)
    await admin.page.screenshot({ path: testInfo.outputPath('admin-permission-desktop.png') })
    await dialog.getByRole('button', { name: '保存用户设置', exact: true }).click()
    await dialog.waitFor({ state: 'hidden' })
    assert.deepEqual((await request(alice.context, 'GET', '/api/v1/auth/me')).permissions, { exchange: false, site_captcha: true })
    assert.deepEqual((await request(bob.context, 'GET', '/api/v1/auth/me')).permissions, { exchange: false, site_captcha: false })
    await alice.page.getByRole('button', { name: '刷新数据', exact: true }).click()
    await expect(alice.page.getByRole('radio', { name: '使用站点打码服务', exact: true })).toBeEnabled()
    await alice.page.getByRole('radio', { name: '使用站点打码服务', exact: true }).check()
    await alice.page.getByRole('button', { name: '保存个人打码配置', exact: true }).click()
    await alice.page.getByText('个人打码配置已保存，仅对你的账号生效。', { exact: true }).waitFor()

    // Both exchange aliases are checked before any account/upstream operation.
    for (const path of ['/api/v1/shop/plans', '/api/v1/shop/plans/run', '/api/v1/shop/exchange']) {
      const response = await alice.context.request.post(origin + path, { headers, data: { account_id: initialA[0].id, goods_id: 'test-only' } })
      assert.equal(response.status(), 403)
    }
    await admin.page.getByRole('button', { name: '管理用户 routine-alice', exact: true }).click()
    dialog = admin.page.getByRole('dialog', { name: 'routine-alice · 用户设置', exact: true })
    await dialog.getByLabel('授予商品兑换权限', { exact: true }).check()
    await dialog.getByLabel('授予站点打码权限', { exact: true }).uncheck()
    await dialog.getByRole('button', { name: '保存用户设置', exact: true }).click()
    await dialog.waitFor({ state: 'hidden' })
    assert.deepEqual((await request(alice.context, 'GET', '/api/v1/auth/me')).permissions, { exchange: true, site_captcha: false })
    assert((await request(alice.context, 'GET', '/api/v1/accounts')).every(a => a.exchange_allowed))
    await alice.page.getByRole('button', { name: '刷新数据', exact: true }).click()
    await alice.page.getByRole('heading', { name: '未获站点服务授权', exact: true }).waitFor()
    await expect(alice.page.getByRole('radio', { name: '使用站点打码服务', exact: true })).toBeDisabled()
    await alice.page.getByRole('radio', { name: '使用自己的打码服务', exact: true }).check()
    await alice.page.getByRole('button', { name: '保存个人打码配置', exact: true }).click()
    await alice.page.getByText('个人打码配置已保存，仅对你的账号生效。', { exact: true }).waitFor()

    await navigate(alice.page, '消息推送')
    await alice.page.getByRole('checkbox', { name: '启用自动推送', exact: true }).check()
    await alice.page.locator('.push-provider-tile[data-provider="webhook"]').click()
    await alice.page.getByRole('dialog').getByRole('button', { name: '配置并添加', exact: true }).click()
    dialog = alice.page.getByRole('dialog')
    await dialog.getByLabel('Webhook 地址', { exact: true }).fill('https://notifications.example/hook')
    await dialog.getByRole('checkbox', { name: '启用这个接收渠道', exact: true }).check()
    await noOverflow(alice.page)
    await alice.page.screenshot({ path: testInfo.outputPath('personal-push-sheet.png') })
    await dialog.getByRole('button', { name: '保存推送配置', exact: true }).click()
    await dialog.waitFor({ state: 'hidden' })
    const pushA = await request(alice.context, 'GET', '/api/v1/push/config'), pushB = await request(bob.context, 'GET', '/api/v1/push/config')
    assert.equal(pushA.enable, true)
    assert.equal(pushA.channels[0].enable, true)
    assert.equal(pushB.enable, false)
    assert.equal(pushB.channels.length, 0)
    assert.equal((await request(alice.context, 'GET', '/api/v1/push/history')).length, 0)

    await bob.page.goto(origin + '/#shop')
    await bob.page.getByText('商品兑换需要管理员授权', { exact: true }).waitFor()
    await noOverflow(bob.page)
    await navigate(bob.page, '打码服务')
    await expect(bob.page.getByRole('radio', { name: '使用自己的打码服务', exact: true })).toBeEnabled()
    await expect(bob.page.getByRole('radio', { name: '使用站点打码服务', exact: true })).toBeDisabled()
    assert.equal(await bob.page.locator('select').count(), 0)
    await noOverflow(bob.page)
    await bob.page.screenshot({ path: testInfo.outputPath('permissions-320px.png'), fullPage: true })
    assert.deepEqual(unsafe, [])
    assert.deepEqual(browserErrors, [])
    await testInfo.attach('isolation-evidence', { body: JSON.stringify({ users: [userA.username, userB.username], independentAccountSettings: true, separatePermissions: true, externalEffects: 0 }), contentType: 'application/json' })
  } finally { for (const context of contexts) await context.close() }
})
